global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'amie-apo-api'
    static_configs:
      - targets: ['amie-api:8000']
    metrics_path: '/metrics'

  - job_name: 'dask-scheduler'
    static_configs:
      - targets: ['amie-api:8787']
    metrics_path: '/metrics'
